<?php
/*
Plugin Name: Categories for links
Plugin URI: https://github.com/gengurke/yourls-categories-for-links
Description: Organize links with categories
Version: 0.1
Author: Florian Klamer
Author URI: https://github.com/gengurke/
*/

// No direct call
if( !defined( 'YOURLS_ABSPATH' ) ) die();

/* Example of an action
 *
 * We're going to add an entry to the menu.
 *
 * The menu is drawn by function yourls_html_menu() in file includes/functions-html.php.
 * Right before the function outputs the closing </ul>, notice the following function call:
 * yourls_do_action( 'admin_menu' );
 * This function says: "hey, for your information, I've just done something called 'admin menu', thought I'd let you know..."
 *
 * We're going to hook into this action and add our menu entry
 */

yourls_add_action( 'admin_menu', 'ozh_sample_add_menu' );
/* This says: when YOURLS does action 'admin_menu', call function 'ozh_sample_add_menu'
 */

function ozh_sample_add_menu() {
    echo '<li><a href="http://ozh.org/">Ozh</a></li>';
}
/* And that's it. Activate the plugin and notice the new menu entry.
 */



/* Example of a filter
 *
 * We're going to modify the <title> of pages in the admin area
 *
 * The <title> tag is generated by function yourls_html_head() in includes/functions-html.php
 * Notice the following function call:
 * $title = yourls_apply_filter( 'html_title', 'YOURLS: Your Own URL Shortener' );
 * This function means: give $title the value "YOURLS: Your Own URL Shortener", unless a
 * filter modifies this value.
 *
 * We're going to hook into this filter and modify this value.
 */

yourls_add_filter( 'html_title', 'ozh_sample_change_title' );
/* This says: when filter 'html_title' is triggered, send its value to function 'ozh_sample_change_title'
 * and use what this function will return.
 */

function ozh_sample_change_title( $value ) {
    $value = $value . ' -- the sample plugin is activated';
    return $value; // a filter *always* has to return a value
}
/* And that's it. Activate the plugin and notice how the page title changes */



    yourls_add_action('html_head', 'cfl_yourls_addnew_js');

    function cfl_yourls_addnew_js()
    {
        $add_to_form = yourls_get_option('add_to_form');
        if (!yourls_is_admin() || $add_to_form == 'no') {
            return;
        }
        ?>
        <script type="text/javascript">

            // Overrride the existing function to include the new fields
            function add_link() {
                if ($('#add-button').hasClass('disabled')) {
                    return false;
                }
                var newurl = $("#add-url").val();
                var nonce = $("#nonce-add").val();
                var cats = $("#cats").val();
                if (!newurl || newurl === 'http://' || newurl === 'https://') {
                    $("#add-url").css({'border-color': 'red', 'color': 'red'}).focus();
                    return;
                }
                $("#add-url").css({'border-color': '#88C0EB', 'color': '#595441'});
                var keyword = $("#add-keyword").val();
                var allfields = $('#new_url_form').serialize(); // Added by KWS
                add_loading("#add-button");
                $.getJSON(
                    ajaxurl,
                    {action: 'add', url: newurl, keyword: keyword, nonce: nonce, allfields: allfields},
                    function (data) {
                        if (data.status === 'success') {
                            $('#main_table tbody').prepend(data.html).trigger("update");
                            $('#nourl_found').css('display', 'none');
                            zebra_table();
                            increment_counter();
                            toggle_share_fill_boxes(data.url.url, data.shorturl, data.url.title);

                        }

                        //reset_url();


                        add_link_reset();
                        end_loading("#add-button");
                        end_disable("#add-button");

                        feedback(data.message, data.status);
                    }
                );
            }

            jQuery(document).ready(function ($) {
                $('#new_url_form').append('<div>GA Tracking Options</div><div class="toggle" id="ga_tracking_options"><?php

                    $sources = kws_yourls_analytics_defaults();

                    foreach ($sources as $source => $value) {
                        $sourceNice = preg_replace('/(?:.*?)\_(.+)/ism', '$1', $source);
                        echo '<label for="' . $source . '" style="padding-left:.75em;">' . $sourceNice . ' <input id="' . $source . '" type="text" size="12" name="' . $source . '" value="' . $value . '" /></label>';
                    }

                    ?></div><div style="clear:both;"></div>');
            });

        </script>

        <?php
    }


?>